# Generated By Github 
# Author : SahrulGunawan / SahrulGunawanID
# Github : 
clear

echo "Main Update"
apt update && apt upgrade -y

echo "x11-repo Update"
apt install x11-repo -y

echo "root-repo Update"
apt install root-repo -y

echo "Install Clang"
apt install clang -y

echo "Install Ndk"
apt install ndk-multilib-native-stubs -y
apt install ndk-multilib-native-static -y
apt install ndk-sysroot -y
apt install ndk-multilib -y

echo "Install cmake or make"
apt install make cmake -y

echo "install build-essential"
apt install build-essential -y

echo "Succces"
